### ISSUE TITLE
I would like to know why markdown-nested.css is not working

### ISSUE THREAD

**Issue by goldcoders** [iandinwoodie/github-markdown-tailwindcss#2]
Im using a [hugo theme](https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter/)

that utilize tailwind css

I manage to use the markdown.css 

but when i try to use the generated markdown-nested.css file from a python command

I dont see any changes like the one when using the markdown.css u provide...

Am I missing something on my postcss.config.js?

this is my post.config.js
```js
const themeDir = __dirname + '/../../';

const purgecss = require('@fullhuman/postcss-purgecss')({

    // Specify the paths to all of the template files in your project
    content: [
        themeDir + 'layouts/**/*.html',
        themeDir + 'exampleSite/content/**/*.html',
        'layouts/**/*.html',
        'content/**/*.html',
    ],

    // This is the function used to extract class names from your templates
    defaultExtractor: content => {
        // Capture as liberally as possible, including things like `h-(screen-1.5)`
        const broadMatches = content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || []

        // Capture classes within other delimiters like .block(class="w-1/2") in Pug
        const innerMatches = content.match(/[^<>"'`\s.()]*[^<>"'`\s.():]/g) || []

        return broadMatches.concat(innerMatches)
    }
})

module.exports = {    
    plugins: [        
        require('postcss-import')({
            path: [themeDir]
            }), 
        require('tailwindcss')(themeDir + 'assets/css/tailwind.config.js'),
        require('autoprefixer')({
            path: [themeDir]
        }),
        ...(process.env.HUGO_ENVIRONMENT === 'production' ? [purgecss] : [])
    ]
}

```

**Comment by iandinwoodie** [comment]
Good evening (or morning in the Philippines). You need to utilize the`postcss-nesting` module to use the nested version with your setup.

Immediately below [this line in your `posts.config.js`](https://github.com/goldcoders/hugo-theme-twal-starter/blob/c3140f4fcebccf4ad52ede81b1ea143973a9f7d8/assets/css/postcss.config.js#L29) add the following:

```js
require('postcss-nesting')({
  path: [themeDir]
}),
```

And, as I'm sure you're aware, you'll need to update [this line in your `styles.css`](https://github.com/goldcoders/hugo-theme-twal-starter/blob/b1fba9789e0d57b3a5bd19a2a6289afd793438ab/assets/css/styles.css#L6) to:

```css
@import "assets/css/markdown-nested";
```

Lastly, here is the link to the official Tailwind documentation section that covers nesting:
https://tailwindcss.com/docs/using-with-preprocessors/#nesting

Please let me know if this does not solve the problem for you.

**Comment by aizkhaj** [comment]
@iandinwoodie Thank you for sharing how you setup for `postcss-nesting`. I was just sleuthing for more details on how Adam (TailwindCSS) or you managed to tackle the nesting issue for markdown stylesheets. The details provided are much appreciated!
